### ISSUE TITLE
Lambdas are just reimplements of ES6 arrow functions

### ISSUE THREAD

**Issue by iddan** [functionaljs/functional-js#10]
Reminding you this is valid now:
```JavaScript
const f = (a, b) => a + b;
```

**Comment by leecrossley** [comment]
Correct, this library intentionally doesn't extend or depend on any of ES5+'s features, such as arrow functions, to prevent conditionalised implementations for different browsers or force transpiling. You're obviously free to use arrow functions with functional js if your environment permits it, such as the example in the [readme](https://github.com/functionaljs/functional-js#curry-es6-example):

Curry ES6 example
```
const add = fjs.curry((a, b) => a + b);

const add3 = add(3);

add(1, 2, 3); // => 6
add3(1, 2, 3, 4, 5); // => 18
```
