### ISSUE TITLE
Fix bower package

### ISSUE THREAD

**Issue by abhisekp** [functionaljs/functional-js#3]
The [**bower search package**](https://bower.io/search/) points to https://github.com/leecrossley/functional-js which doesn't exist.

It should point to https://github.com/functionaljs/functional-js

**Comment by leecrossley** [comment]
Yep, good point. Any idea how to update the url with bower? `register` seems to be a one time shot.

**Comment by abhisekp** [comment]
No idea :no_good:

**Comment by leecrossley** [comment]
Released under `functional-js`

```
bower info functional-js#0.8.0
```

**Comment by pavelsof** [comment]
It should be updated here as well:
http://functionaljs.com/installation/
