### ISSUE TITLE
Replace fjs.isArray function

### ISSUE THREAD

**Issue by vishalknitian** [functionaljs/functional-js#4]
Array.isArray is native JavaScript and easy to read.

The isArray function is part of the Array.prototype object in ES2015

**Comment by leecrossley** [comment]
Thanks for your interest in functional.js! This library intentionally doesn't extend any of JavaScript’s standard built-in objects such as isArray, or use native functions that conditionalise implementations.

**Comment by vishalknitian** [comment]
Good Idea, I will keep an eye on the issues. I would be glad to contribute. :)
