### ISSUE TITLE
Curried function cannot be used in fold

### ISSUE THREAD

**Issue by taufiqkh** [functionaljs/functional-js#5]
I am attempting to fold a curried function across an array in the following way:
```javascript
let curryGrow = fjs.curry(function grow(separator, acc, elem) {
  return acc + '' + elem + separator;
});
let growComma = curryGrow(',');
let result = fjs.fold(growComma, 'z')(['a', 'b', 'c']);
```
The final value of result in this case is the String '201000za,b,c,', while I would have expected the value to be 'za,b,c,'.

This can be worked around with an explicit function:
```javascript
let grow = function(separator, acc, elem) {
  return acc + '' + elem + separator;
};
let growComma = function(acc, elem) {
  return grow(',', acc, elem);
};
let result = fjs.fold(growComma, 'z')(['a', 'b', 'c']);
```

Am I using the library correctly? I was attempting to do something the equivalent of in Haskell:
```haskell
grow :: String -> String -> String -> String
grow separator acc n = acc ++ n ++ separator
foldl (grow ",") "z" ["a", "b", "c"]
```
The code used is just intended as a minimalist example, I do realise there are better ways to do it.

Edit: This is in Node.js 4.4.5

**Comment by leecrossley** [comment]
Hi @taufiqkh, firstly thanks for using functional-js 👍

There's a more _javascript-y_ way to achieve this using bind before the fold, rather than another curry.

```
        let grow = (separator, acc, elem) => {
            return `${acc}${elem}${separator}`;
        };

        let growComma = fjs.fold(grow.bind(this, ","));

        let result = growComma("z", ["a", "b", "c"]);

        expect(result).toEqual("za,b,c,");
```

If I've not answered your question properly, please feel free to re-open!

**Comment by taufiqkh** [comment]
Ah, great, thanks.
