### ISSUE TITLE
.each/.fold/.. on a NodeList

### ISSUE THREAD

**Issue by pavelsof** [functionaljs/functional-js#9]
First of all, thank you for contributing this library, I find it nice and useful!

I ran into an issue trying to fold a NodeList. Consider this:

```js
fjs.fold(function(data, field) {
    data[field.name] = field.value;
    return data;
}, {}, form.querySelector('[name]'));
```

This is failing silently, apparently because `fjs.isArray` returns false when given a NodeList. It might be a rash suggestion, but why not remove that check in `fjs.each`? Then (1) array-like structures (another example is function arguments) would be handled OK, and (2) some kind of error will be raised when trying to use a non-array (I would argue it is preferable not to let stuff like `fjs.each(console.log, 42)` go through without a complaint).

**Comment by leecrossley** [comment]
I'd prefer to keep it as it is and ensure a bonafide array is passed (that passes the check).

You could do something like this for working with the DOM and NodeLists:

`[].slice.call(form.querySelector("[name]"));`

Quick full DOM example:

```
const $ = document.querySelectorAll.bind(document);
let prices = [].slice.call($(".price"));
fjs.fold((a, b) => { return a + b; }, 0, prices);
```
